apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: dummy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    id: dummy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      id: dummy
  template:
    metadata:
      labels:
        app: nginx
        id: dummy
    spec:
      containers:
        - image: nginx:1.17.5-alpine
          imagePullPolicy: IfNotPresent
          name: dummy
          ports:
            - containerPort: 80
